name: Regenerate containers

on:
  workflow_dispatch:

jobs:
  install_shop_with_module:
    strategy:
      matrix:
        php: [ '8.3' ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current module
        uses: actions/checkout@v4
        with:
          path: ./

      - name: Prepare image
        run: |
          cd containers/php-fpm/bases/${{ matrix.php }}
          docker build -t siegfuse/php-fpm-production-base:${{ matrix.php }} .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Push image
        run: |
          docker push siegfuse/php-fpm-production-base:${{ matrix.php }}